import type { ShelterSeedData } from './california-shelters';

export const alabamaShelters: ShelterSeedData[] = [
    {
        name: 'Jefferson County Animal Control',
        county: 'Jefferson',
        state: 'AL',
        address: '1400 1st Ave N, Birmingham, AL 35203',
        phone: '(205) 325-5200',
        websiteUrl: 'https://www.jccal.org/Default.asp?ID=459&pg=Animal+Control',
        totalIntakeAnnual: 7000,
        totalEuthanizedAnnual: 2100,
        dataYear: 2024,
        dataSourceName: 'Jefferson County Government',
        dataSourceUrl: 'https://www.jccal.org/Default.asp?ID=459&pg=Animal+Control',
        countyPopulation: 674721,
        totalReturnedToOwner: 700,
        totalTransferred: 800,
        priorYearIntake: 6800,
        priorYearEuthanized: 2108,
        priorDataYear: 2023,
    },
    {
        name: 'Mobile County Animal Shelter',
        county: 'Mobile',
        state: 'AL',
        address: '7665 Howells Ferry Rd, Mobile, AL 36618',
        phone: '(251) 574-3647',
        websiteUrl: 'https://www.mobilecountyal.gov/government/animal-shelter/',
        totalIntakeAnnual: 6000,
        totalEuthanizedAnnual: 1800,
        dataYear: 2024,
        dataSourceName: 'Mobile County Government',
        dataSourceUrl: 'https://www.mobilecountyal.gov/government/animal-shelter/',
        countyPopulation: 414809,
        totalReturnedToOwner: 500,
        totalTransferred: 600,
        priorYearIntake: 5800,
        priorYearEuthanized: 1798,
        priorDataYear: 2023,
    },
    {
        name: 'Montgomery Humane Society',
        county: 'Montgomery',
        state: 'AL',
        address: '1150 John Overton Dr, Montgomery, AL 36110',
        phone: '(334) 409-0622',
        websiteUrl: 'https://www.montgomeryhumane.com',
        totalIntakeAnnual: 5500,
        totalEuthanizedAnnual: 1375,
        dataYear: 2024,
        dataSourceName: 'Montgomery Humane Society',
        dataSourceUrl: 'https://www.montgomeryhumane.com/about/',
        countyPopulation: 228954,
        totalReturnedToOwner: 500,
        totalTransferred: 600,
        priorYearIntake: 5300,
        priorYearEuthanized: 1378,
        priorDataYear: 2023,
    },
    {
        name: 'Huntsville Animal Services',
        county: 'Madison',
        state: 'AL',
        address: '4950 Triana Blvd SW, Huntsville, AL 35805',
        phone: '(256) 883-3783',
        websiteUrl: 'https://www.huntsvilleal.gov/residents/neighborhoods/animal-services/',
        totalIntakeAnnual: 4500,
        totalEuthanizedAnnual: 675,
        dataYear: 2024,
        dataSourceName: 'Huntsville Animal Services',
        dataSourceUrl: 'https://www.huntsvilleal.gov/residents/neighborhoods/animal-services/',
        countyPopulation: 395279,
        totalReturnedToOwner: 600,
        totalTransferred: 700,
        priorYearIntake: 4300,
        priorYearEuthanized: 645,
        priorDataYear: 2023,
    },
    {
        name: 'Tuscaloosa Metro Animal Shelter',
        county: 'Tuscaloosa',
        state: 'AL',
        address: '3140 35th St, Tuscaloosa, AL 35401',
        phone: '(205) 752-1313',
        websiteUrl: 'https://www.tuscaloosametroanimalshelter.org',
        totalIntakeAnnual: 4000,
        totalEuthanizedAnnual: 1000,
        dataYear: 2024,
        dataSourceName: 'Tuscaloosa Metro Animal Shelter',
        dataSourceUrl: 'https://www.tuscaloosametroanimalshelter.org',
        countyPopulation: 227036,
        totalReturnedToOwner: 400,
        totalTransferred: 500,
        priorYearIntake: 3800,
        priorYearEuthanized: 988,
        priorDataYear: 2023,
    },
];
