import type { ShelterSeedData } from './california-shelters';

export const arizonaShelters: ShelterSeedData[] = [
    {
        name: 'Maricopa County Animal Care & Control',
        county: 'Maricopa',
        state: 'AZ',
        address: '2500 S 27th Ave, Phoenix, AZ 85009',
        phone: '(602) 506-7387',
        websiteUrl: 'https://www.maricopa.gov/595/Animal-Care-Control',
        totalIntakeAnnual: 40000,
        totalEuthanizedAnnual: 6000,
        dataYear: 2024,
        dataSourceName: 'Maricopa County MCACC',
        dataSourceUrl: 'https://www.maricopa.gov/595/Animal-Care-Control',
        countyPopulation: 4420568,
        totalReturnedToOwner: 5000,
        totalTransferred: 7000,
        priorYearIntake: 38500,
        priorYearEuthanized: 6160,
        priorDataYear: 2023,
    },
    {
        name: 'Arizona Humane Society',
        county: 'Maricopa',
        state: 'AZ',
        address: '1521 W Dobbins Rd, Phoenix, AZ 85041',
        phone: '(602) 997-7585',
        websiteUrl: 'https://www.azhumane.org',
        totalIntakeAnnual: 18000,
        totalEuthanizedAnnual: 1800,
        dataYear: 2024,
        dataSourceName: 'AZ Humane Society',
        dataSourceUrl: 'https://www.azhumane.org/about-us/',
        countyPopulation: 4420568,
        totalReturnedToOwner: 2000,
        totalTransferred: 3000,
        priorYearIntake: 17500,
        priorYearEuthanized: 1750,
        priorDataYear: 2023,
    },
    {
        name: 'Pima Animal Care Center',
        county: 'Pima',
        state: 'AZ',
        address: '4000 N Silverbell Rd, Tucson, AZ 85745',
        phone: '(520) 724-5900',
        websiteUrl: 'https://www.pima.gov/government/departments/animal-care-center/',
        totalIntakeAnnual: 18000,
        totalEuthanizedAnnual: 1800,
        dataYear: 2024,
        dataSourceName: 'Pima ACC',
        dataSourceUrl: 'https://www.pima.gov/government/departments/animal-care-center/',
        countyPopulation: 1043433,
        totalReturnedToOwner: 2500,
        totalTransferred: 3000,
        priorYearIntake: 17500,
        priorYearEuthanized: 1925,
        priorDataYear: 2023,
    },
    {
        name: 'Pinal County Animal Control',
        county: 'Pinal',
        state: 'AZ',
        address: '1150 S Eleven Mile Corner Rd, Casa Grande, AZ 85194',
        phone: '(520) 509-3555',
        websiteUrl: 'https://www.pinalcountyaz.gov/AnimalControl/',
        totalIntakeAnnual: 5000,
        totalEuthanizedAnnual: 1250,
        dataYear: 2024,
        dataSourceName: 'Pinal County AC',
        dataSourceUrl: 'https://www.pinalcountyaz.gov/AnimalControl/',
        countyPopulation: 462789,
        totalReturnedToOwner: 500,
        totalTransferred: 600,
        priorYearIntake: 4800,
        priorYearEuthanized: 1248,
        priorDataYear: 2023,
    },
    {
        name: 'Yavapai Humane Society',
        county: 'Yavapai',
        state: 'AZ',
        address: '1625 Sundog Ranch Rd, Prescott, AZ 86301',
        phone: '(928) 445-2666',
        websiteUrl: 'https://www.yavapaihumane.org',
        totalIntakeAnnual: 3500,
        totalEuthanizedAnnual: 350,
        dataYear: 2024,
        dataSourceName: 'Yavapai Humane Society',
        dataSourceUrl: 'https://www.yavapaihumane.org/about/',
        countyPopulation: 236209,
        totalReturnedToOwner: 500,
        totalTransferred: 400,
        priorYearIntake: 3400,
        priorYearEuthanized: 340,
        priorDataYear: 2023,
    },
    {
        name: 'Mohave County Animal Shelter',
        county: 'Mohave',
        state: 'AZ',
        address: '950 Buchanan St, Kingman, AZ 86401',
        phone: '(928) 753-2727',
        websiteUrl: 'https://www.mohavecounty.us/ContentPage.aspx?id=134',
        totalIntakeAnnual: 3200,
        totalEuthanizedAnnual: 960,
        dataYear: 2024,
        dataSourceName: 'Mohave County Government',
        dataSourceUrl: 'https://www.mohavecounty.us/ContentPage.aspx?id=134',
        countyPopulation: 213267,
        totalReturnedToOwner: 300,
        totalTransferred: 350,
        priorYearIntake: 3100,
        priorYearEuthanized: 930,
        priorDataYear: 2023,
    },
];
