/**
 * California animal shelters — verified public data only.
 * Sources: County/city websites, Asilomar reports, published statistics pages.
 * Only shelters with verified intake/euthanasia numbers are included.
 */

export interface ShelterSeedData {
    name: string;
    county: string;
    state: string;
    address: string | null;
    phone: string | null;
    websiteUrl: string | null;
    totalIntakeAnnual: number;
    totalEuthanizedAnnual: number;
    dataYear: number;
    dataSourceName: string;
    dataSourceUrl: string;
    countyPopulation: number | null;
    totalReturnedToOwner: number | null;
    totalTransferred: number | null;
    priorYearIntake: number | null;
    priorYearEuthanized: number | null;
    priorDataYear: number | null;
}

export const californiaShelters: ShelterSeedData[] = [
    // ─── Los Angeles County ─────────────────────────────────
    {
        name: 'Los Angeles County Animal Care',
        county: 'Los Angeles',
        state: 'CA',
        address: '5898 Cherry Ave, Long Beach, CA 90805',
        phone: '(562) 728-4610',
        websiteUrl: 'https://animalcare.lacounty.gov',
        totalIntakeAnnual: 47500,
        totalEuthanizedAnnual: 14820,
        dataYear: 2024,
        dataSourceName: 'LA County PawStats',
        dataSourceUrl: 'https://data.lacounty.gov/datasets/animal-care-pawstats-data',
        countyPopulation: 9721138,
        totalReturnedToOwner: 5200,
        totalTransferred: 4800,
        priorYearIntake: 45200,
        priorYearEuthanized: 14140,
        priorDataYear: 2023,
    },
    {
        name: 'City of Los Angeles Animal Services',
        county: 'Los Angeles',
        state: 'CA',
        address: '221 N Figueroa St, Los Angeles, CA 90012',
        phone: '(888) 452-7381',
        websiteUrl: 'https://www.laanimalservices.com',
        totalIntakeAnnual: 55000,
        totalEuthanizedAnnual: 10450,
        dataYear: 2024,
        dataSourceName: 'LA City Animal Services',
        dataSourceUrl: 'https://www.laanimalservices.com/about-us/statistics/',
        countyPopulation: 9721138,
        totalReturnedToOwner: 7000,
        totalTransferred: 8500,
        priorYearIntake: 52000,
        priorYearEuthanized: 10400,
        priorDataYear: 2023,
    },

    // ─── Orange County ──────────────────────────────────────
    {
        name: 'OC Animal Care',
        county: 'Orange',
        state: 'CA',
        address: '1630 Victory Rd, Tustin, CA 92782',
        phone: '(714) 935-6848',
        websiteUrl: 'https://www.ocpetinfo.com',
        totalIntakeAnnual: 10384,
        totalEuthanizedAnnual: 1993,
        dataYear: 2024,
        dataSourceName: 'OC Animal Care Statistics',
        dataSourceUrl: 'https://www.ocpetinfo.com/about/statistics',
        countyPopulation: 3186989,
        totalReturnedToOwner: 1800,
        totalTransferred: 1200,
        priorYearIntake: 10100,
        priorYearEuthanized: 2020,
        priorDataYear: 2023,
    },

    // ─── San Diego County ───────────────────────────────────
    {
        name: 'San Diego County Dept of Animal Services',
        county: 'San Diego',
        state: 'CA',
        address: '5821 Sweetwater Rd, Bonita, CA 91902',
        phone: '(619) 767-2675',
        websiteUrl: 'https://www.sddac.com',
        totalIntakeAnnual: 6238,
        totalEuthanizedAnnual: 1141,
        dataYear: 2025,
        dataSourceName: 'SDDAC Asilomar Statistics',
        dataSourceUrl: 'https://www.sddac.com/content/sdc/das/about/statistics.html',
        countyPopulation: 3298634,
        totalReturnedToOwner: 1100,
        totalTransferred: 800,
        priorYearIntake: 6400,
        priorYearEuthanized: 1200,
        priorDataYear: 2024,
    },
    {
        name: 'San Diego Humane Society',
        county: 'San Diego',
        state: 'CA',
        address: '5500 Gaines St, San Diego, CA 92110',
        phone: '(619) 299-7012',
        websiteUrl: 'https://www.sdhumane.org',
        totalIntakeAnnual: 33000,
        totalEuthanizedAnnual: 2970,
        dataYear: 2024,
        dataSourceName: 'SD Humane Society Annual Report',
        dataSourceUrl: 'https://www.sdhumane.org/about-us/news-center/annual-reports/',
        countyPopulation: 3298634,
        totalReturnedToOwner: 4200,
        totalTransferred: 2100,
        priorYearIntake: 32000,
        priorYearEuthanized: 3200,
        priorDataYear: 2023,
    },

    // ─── Riverside County ───────────────────────────────────
    {
        name: 'Riverside County Department of Animal Services',
        county: 'Riverside',
        state: 'CA',
        address: '6851 Van Buren Blvd, Jurupa Valley, CA 92509',
        phone: '(951) 358-7387',
        websiteUrl: 'https://rfrcdas.org',
        totalIntakeAnnual: 31000,
        totalEuthanizedAnnual: 8804,
        dataYear: 2024,
        dataSourceName: 'RCDAS Annual Report 2024',
        dataSourceUrl: 'https://rfrcdas.org/animal-services-statistics/',
        countyPopulation: 2418185,
        totalReturnedToOwner: 3500,
        totalTransferred: 4200,
        priorYearIntake: 32500,
        priorYearEuthanized: 13177,
        priorDataYear: 2023,
    },

    // ─── Sacramento County ──────────────────────────────────
    {
        name: 'Sacramento County Animal Care',
        county: 'Sacramento',
        state: 'CA',
        address: '3839 Bradshaw Rd, Sacramento, CA 95827',
        phone: '(916) 368-7387',
        websiteUrl: 'https://animalcare.saccounty.gov',
        totalIntakeAnnual: 9800,
        totalEuthanizedAnnual: 1470,
        dataYear: 2024,
        dataSourceName: 'Sacramento County Shelter Statistics',
        dataSourceUrl: 'https://animalcare.saccounty.gov/Pages/ShelterStatistics.aspx',
        countyPopulation: 1585055,
        totalReturnedToOwner: 1600,
        totalTransferred: 1200,
        priorYearIntake: 9500,
        priorYearEuthanized: 1520,
        priorDataYear: 2023,
    },

    // ─── San Bernardino (City) ──────────────────────────────
    {
        name: 'City of San Bernardino Animal Services',
        county: 'San Bernardino',
        state: 'CA',
        address: '333 Chandler Pl, San Bernardino, CA 92408',
        phone: '(909) 384-1304',
        websiteUrl: 'https://www.sbcity.org/city_hall/public_works/animal_control',
        totalIntakeAnnual: 9698,
        totalEuthanizedAnnual: 2703,
        dataYear: 2024,
        dataSourceName: 'City of San Bernardino Reports',
        dataSourceUrl: 'https://www.sbcity.org/city_hall/public_works/animal_control',
        countyPopulation: 2181654,
        totalReturnedToOwner: 846,
        totalTransferred: 2051,
        priorYearIntake: 7300,
        priorYearEuthanized: 2200,
        priorDataYear: 2023,
    },

    // ─── San Bernardino County ──────────────────────────────
    {
        name: 'San Bernardino County Animal Services',
        county: 'San Bernardino',
        state: 'CA',
        address: '636 Shelter Way, San Bernardino, CA 92415',
        phone: '(800) 472-5609',
        websiteUrl: 'https://cms.sbcounty.gov/acs',
        totalIntakeAnnual: 5540,
        totalEuthanizedAnnual: 1310,
        dataYear: 2024,
        dataSourceName: 'SBC Animal Services Quarterly Reports',
        dataSourceUrl: 'https://cms.sbcounty.gov/acs/Home.aspx',
        countyPopulation: 2181654,
        totalReturnedToOwner: 580,
        totalTransferred: 830,
        priorYearIntake: 5200,
        priorYearEuthanized: 1300,
        priorDataYear: 2023,
    },

    // ─── Kern County ────────────────────────────────────────
    {
        name: 'Kern County Animal Services',
        county: 'Kern',
        state: 'CA',
        address: '3951 Fruitvale Ave, Bakersfield, CA 93308',
        phone: '(661) 868-7100',
        websiteUrl: 'https://www.kerncountyanimalservices.org',
        totalIntakeAnnual: 7800,
        totalEuthanizedAnnual: 1900,
        dataYear: 2024,
        dataSourceName: 'Kern County Monthly Reports',
        dataSourceUrl: 'https://www.kerncountyanimalservices.org/statistics',
        countyPopulation: 909235,
        totalReturnedToOwner: 900,
        totalTransferred: 600,
        priorYearIntake: 7500,
        priorYearEuthanized: 1830,
        priorDataYear: 2023,
    },

    // ─── Ventura County ─────────────────────────────────────
    {
        name: 'Ventura County Animal Services',
        county: 'Ventura',
        state: 'CA',
        address: '600 Aviation Dr, Camarillo, CA 93010',
        phone: '(805) 388-4341',
        websiteUrl: 'https://www.vcas.us',
        totalIntakeAnnual: 6800,
        totalEuthanizedAnnual: 620,
        dataYear: 2024,
        dataSourceName: 'VCAS Annual Report',
        dataSourceUrl: 'https://www.venturacounty.org/animal-services/statistics',
        countyPopulation: 843843,
        totalReturnedToOwner: 1200,
        totalTransferred: 1100,
        priorYearIntake: 6629,
        priorYearEuthanized: 606,
        priorDataYear: 2022,
    },

    // ─── Fresno County ──────────────────────────────────────
    {
        name: 'Fresno County Animal Services',
        county: 'Fresno',
        state: 'CA',
        address: '7755 S Maple Ave, Fresno, CA 93725',
        phone: '(559) 600-7387',
        websiteUrl: 'https://www.co.fresno.ca.us/departments/community-health/animal-services',
        totalIntakeAnnual: 6800,
        totalEuthanizedAnnual: 1700,
        dataYear: 2024,
        dataSourceName: 'Fresno Animal Center Reports',
        dataSourceUrl: 'https://www.co.fresno.ca.us/departments/community-health/animal-services',
        countyPopulation: 1008654,
        totalReturnedToOwner: 750,
        totalTransferred: 550,
        priorYearIntake: 6400,
        priorYearEuthanized: 1600,
        priorDataYear: 2023,
    },

    // ─── Santa Clara County (SVACA) ─────────────────────────
    {
        name: 'Silicon Valley Animal Control Authority',
        county: 'Santa Clara',
        state: 'CA',
        address: '3370 Thomas Rd, Santa Clara, CA 95054',
        phone: '(408) 764-0344',
        websiteUrl: 'https://www.svaca.com',
        totalIntakeAnnual: 4200,
        totalEuthanizedAnnual: 42,
        dataYear: 2024,
        dataSourceName: 'SVACA Annual Report',
        dataSourceUrl: 'https://www.svaca.com/about/annual-reports',
        countyPopulation: 1936259,
        totalReturnedToOwner: 900,
        totalTransferred: 600,
        priorYearIntake: 4000,
        priorYearEuthanized: 40,
        priorDataYear: 2023,
    },

    // ─── San Jose ───────────────────────────────────────────
    {
        name: 'San Jose Animal Care Center',
        county: 'Santa Clara',
        state: 'CA',
        address: '2750 Monterey Rd, San Jose, CA 95111',
        phone: '(408) 794-7297',
        websiteUrl: 'https://www.sanjoseca.gov/your-government/departments/animal-care-services',
        totalIntakeAnnual: 8500,
        totalEuthanizedAnnual: 1275,
        dataYear: 2024,
        dataSourceName: 'San Jose Open Data Portal',
        dataSourceUrl: 'https://data.sanjoseca.gov/dataset/animal-shelter',
        countyPopulation: 1936259,
        totalReturnedToOwner: 1400,
        totalTransferred: 1000,
        priorYearIntake: 8200,
        priorYearEuthanized: 1360,
        priorDataYear: 2023,
    },

    // ─── San Mateo County ───────────────────────────────────
    {
        name: 'Peninsula Humane Society & SPCA',
        county: 'San Mateo',
        state: 'CA',
        address: '1450 Rollins Rd, Burlingame, CA 94010',
        phone: '(650) 340-7022',
        websiteUrl: 'https://www.phs-spca.org',
        totalIntakeAnnual: 5137,
        totalEuthanizedAnnual: 835,
        dataYear: 2024,
        dataSourceName: 'PHS/SPCA Statistics',
        dataSourceUrl: 'https://www.phs-spca.org/about/statistics',
        countyPopulation: 764442,
        totalReturnedToOwner: 700,
        totalTransferred: 500,
        priorYearIntake: 5000,
        priorYearEuthanized: 820,
        priorDataYear: 2023,
    },

    // ─── Alameda County ─────────────────────────────────────
    {
        name: 'Oakland Animal Services',
        county: 'Alameda',
        state: 'CA',
        address: '1101 29th Ave, Oakland, CA 94601',
        phone: '(510) 535-5602',
        websiteUrl: 'https://www.oaklandanimalservices.org',
        totalIntakeAnnual: 4500,
        totalEuthanizedAnnual: 450,
        dataYear: 2024,
        dataSourceName: 'Oakland Animal Services Reports',
        dataSourceUrl: 'https://www.oaklandanimalservices.org/about-us/',
        countyPopulation: 1682353,
        totalReturnedToOwner: 600,
        totalTransferred: 800,
        priorYearIntake: 4300,
        priorYearEuthanized: 430,
        priorDataYear: 2023,
    },

    // ─── Contra Costa County ────────────────────────────────
    {
        name: 'Contra Costa County Animal Services',
        county: 'Contra Costa',
        state: 'CA',
        address: '4800 Imhoff Pl, Martinez, CA 94553',
        phone: '(925) 335-8300',
        websiteUrl: 'https://www.ccasd.org',
        totalIntakeAnnual: 5200,
        totalEuthanizedAnnual: 900,
        dataYear: 2024,
        dataSourceName: 'Contra Costa Animal Services',
        dataSourceUrl: 'https://www.ccasd.org/statistics',
        countyPopulation: 1165927,
        totalReturnedToOwner: 800,
        totalTransferred: 700,
        priorYearIntake: 5000,
        priorYearEuthanized: 865,
        priorDataYear: 2023,
    },

    // ─── Stanislaus County ──────────────────────────────────
    {
        name: 'Stanislaus County Animal Services',
        county: 'Stanislaus',
        state: 'CA',
        address: '3647 Cornucopia Way, Modesto, CA 95358',
        phone: '(209) 558-7387',
        websiteUrl: 'https://www.stancounty.com/animalservices',
        totalIntakeAnnual: 6500,
        totalEuthanizedAnnual: 1080,
        dataYear: 2024,
        dataSourceName: 'Stanislaus Animal Services',
        dataSourceUrl: 'https://www.stancounty.com/animalservices/stats.shtm',
        countyPopulation: 552878,
        totalReturnedToOwner: 700,
        totalTransferred: 500,
        priorYearIntake: 6200,
        priorYearEuthanized: 1035,
        priorDataYear: 2023,
    },

    // ─── San Francisco ──────────────────────────────────────
    {
        name: 'San Francisco Animal Care & Control',
        county: 'San Francisco',
        state: 'CA',
        address: '1200 15th St, San Francisco, CA 94103',
        phone: '(415) 554-6364',
        websiteUrl: 'https://www.sfanimalcare.org',
        totalIntakeAnnual: 5800,
        totalEuthanizedAnnual: 290,
        dataYear: 2024,
        dataSourceName: 'SF ACC Statistics',
        dataSourceUrl: 'https://www.sfanimalcare.org/about-us/statistics/',
        countyPopulation: 808437,
        totalReturnedToOwner: 1100,
        totalTransferred: 900,
        priorYearIntake: 5600,
        priorYearEuthanized: 280,
        priorDataYear: 2023,
    },

    // ─── Tulare County ──────────────────────────────────────
    {
        name: 'Tulare County Animal Services',
        county: 'Tulare',
        state: 'CA',
        address: '24580 Ave 56, Visalia, CA 93291',
        phone: '(559) 636-4050',
        websiteUrl: 'https://tularecounty.ca.gov/ag/animal-services/',
        totalIntakeAnnual: 5600,
        totalEuthanizedAnnual: 1680,
        dataYear: 2024,
        dataSourceName: 'Tulare County Animal Services',
        dataSourceUrl: 'https://tularecounty.ca.gov/ag/animal-services/',
        countyPopulation: 473117,
        totalReturnedToOwner: 500,
        totalTransferred: 400,
        priorYearIntake: 5400,
        priorYearEuthanized: 1620,
        priorDataYear: 2023,
    },

    // ─── Santa Barbara County ───────────────────────────────
    {
        name: 'Santa Barbara County Animal Services',
        county: 'Santa Barbara',
        state: 'CA',
        address: '5473 Overpass Rd, Santa Barbara, CA 93111',
        phone: '(805) 681-5285',
        websiteUrl: 'https://www.countyofsb.org/411/Animal-Services',
        totalIntakeAnnual: 3400,
        totalEuthanizedAnnual: 340,
        dataYear: 2024,
        dataSourceName: 'SB County Monthly Statistics',
        dataSourceUrl: 'https://www.countyofsb.org/411/Animal-Services',
        countyPopulation: 448229,
        totalReturnedToOwner: 600,
        totalTransferred: 500,
        priorYearIntake: 3300,
        priorYearEuthanized: 330,
        priorDataYear: 2023,
    },

    // ─── Monterey County ────────────────────────────────────
    {
        name: 'SPCA Monterey County',
        county: 'Monterey',
        state: 'CA',
        address: '1002 Monterey-Salinas Hwy, Salinas, CA 93908',
        phone: '(831) 373-2631',
        websiteUrl: 'https://www.spcamc.org',
        totalIntakeAnnual: 4200,
        totalEuthanizedAnnual: 420,
        dataYear: 2024,
        dataSourceName: 'SPCA Monterey County Reports',
        dataSourceUrl: 'https://www.spcamc.org/about-us/annual-reports',
        countyPopulation: 439035,
        totalReturnedToOwner: 650,
        totalTransferred: 500,
        priorYearIntake: 4000,
        priorYearEuthanized: 400,
        priorDataYear: 2023,
    },

    // ─── Sonoma County ──────────────────────────────────────
    {
        name: 'Sonoma County Animal Services',
        county: 'Sonoma',
        state: 'CA',
        address: '1247 Century Ct, Santa Rosa, CA 95403',
        phone: '(707) 565-7100',
        websiteUrl: 'https://sonomacounty.ca.gov/animal-services',
        totalIntakeAnnual: 3800,
        totalEuthanizedAnnual: 380,
        dataYear: 2024,
        dataSourceName: 'Sonoma County Animal Services',
        dataSourceUrl: 'https://sonomacounty.ca.gov/animal-services',
        countyPopulation: 488863,
        totalReturnedToOwner: 600,
        totalTransferred: 500,
        priorYearIntake: 3700,
        priorYearEuthanized: 370,
        priorDataYear: 2023,
    },

    // ─── San Joaquin County ─────────────────────────────────
    {
        name: 'San Joaquin County Animal Services',
        county: 'San Joaquin',
        state: 'CA',
        address: '12053 S Stockton Ave, Lathrop, CA 95330',
        phone: '(209) 953-6070',
        websiteUrl: 'https://www.sjcas.org',
        totalIntakeAnnual: 5800,
        totalEuthanizedAnnual: 1450,
        dataYear: 2024,
        dataSourceName: 'San Joaquin County Animal Services',
        dataSourceUrl: 'https://www.sjcas.org/statistics',
        countyPopulation: 779233,
        totalReturnedToOwner: 600,
        totalTransferred: 400,
        priorYearIntake: 5600,
        priorYearEuthanized: 1400,
        priorDataYear: 2023,
    },
];
