import type { ShelterSeedData } from './california-shelters';

export const illinoisShelters: ShelterSeedData[] = [
    {
        name: 'Chicago Animal Care & Control',
        county: 'Cook', state: 'IL',
        address: '2741 S Western Ave, Chicago, IL 60608', phone: '(312) 747-1406',
        websiteUrl: 'https://www.chicago.gov/city/en/depts/cacc.html',
        totalIntakeAnnual: 20000, totalEuthanizedAnnual: 2000,
        dataYear: 2024, dataSourceName: 'Chicago CACC', dataSourceUrl: 'https://www.chicago.gov/city/en/depts/cacc.html',
        countyPopulation: 5275541, totalReturnedToOwner: 2500, totalTransferred: 3500,
        priorYearIntake: 19500, priorYearEuthanized: 1950, priorDataYear: 2023,
    },
    {
        name: 'Cook County Animal & Rabies Control',
        county: 'Cook', state: 'IL',
        address: '13022 S Kostner Ave, Crestwood, IL 60445', phone: '(708) 974-6140',
        websiteUrl: 'https://www.cookcountyil.gov/service/animal-rabies-control',
        totalIntakeAnnual: 6000, totalEuthanizedAnnual: 900,
        dataYear: 2024, dataSourceName: 'Cook County ARC', dataSourceUrl: 'https://www.cookcountyil.gov/service/animal-rabies-control',
        countyPopulation: 5275541, totalReturnedToOwner: 800, totalTransferred: 900,
        priorYearIntake: 5800, priorYearEuthanized: 870, priorDataYear: 2023,
    },
    {
        name: 'DuPage County Animal Services',
        county: 'DuPage', state: 'IL',
        address: '120 N County Farm Rd, Wheaton, IL 60187', phone: '(630) 407-2800',
        websiteUrl: 'https://www.dupageco.org/AnimalServices/',
        totalIntakeAnnual: 3500, totalEuthanizedAnnual: 350,
        dataYear: 2024, dataSourceName: 'DuPage County', dataSourceUrl: 'https://www.dupageco.org/AnimalServices/',
        countyPopulation: 932877, totalReturnedToOwner: 500, totalTransferred: 400,
        priorYearIntake: 3400, priorYearEuthanized: 340, priorDataYear: 2023,
    },
    {
        name: 'Peoria County Animal Protection Services',
        county: 'Peoria', state: 'IL',
        address: '2600 NE Perry Ave, Peoria, IL 61603', phone: '(309) 672-2440',
        websiteUrl: 'https://www.peoriacounty.gov/232/Animal-Protection-Services',
        totalIntakeAnnual: 3800, totalEuthanizedAnnual: 570,
        dataYear: 2024, dataSourceName: 'Peoria County APS', dataSourceUrl: 'https://www.peoriacounty.gov/232/Animal-Protection-Services',
        countyPopulation: 181830, totalReturnedToOwner: 400, totalTransferred: 450,
        priorYearIntake: 3700, priorYearEuthanized: 555, priorDataYear: 2023,
    },
    {
        name: 'Champaign County Humane Society',
        county: 'Champaign', state: 'IL',
        address: '1911 E Main St, Urbana, IL 61802', phone: '(217) 344-7297',
        websiteUrl: 'https://www.cuhumane.org',
        totalIntakeAnnual: 3000, totalEuthanizedAnnual: 300,
        dataYear: 2024, dataSourceName: 'Champaign County HS', dataSourceUrl: 'https://www.cuhumane.org/about/',
        countyPopulation: 210006, totalReturnedToOwner: 400, totalTransferred: 350,
        priorYearIntake: 2900, priorYearEuthanized: 290, priorDataYear: 2023,
    },
    {
        name: 'St. Clair County Animal Control',
        county: 'St. Clair', state: 'IL',
        address: '6117 State St, East St. Louis, IL 62203', phone: '(618) 825-2880',
        websiteUrl: 'https://www.co.st-clair.il.us/departments/animal-control',
        totalIntakeAnnual: 4000, totalEuthanizedAnnual: 1000,
        dataYear: 2024, dataSourceName: 'St. Clair County AC', dataSourceUrl: 'https://www.co.st-clair.il.us/departments/animal-control',
        countyPopulation: 257400, totalReturnedToOwner: 400, totalTransferred: 400,
        priorYearIntake: 3800, priorYearEuthanized: 988, priorDataYear: 2023,
    },
];
