import type { ShelterSeedData } from './california-shelters';

export const indianaShelters: ShelterSeedData[] = [
    {
        name: 'Indianapolis Animal Care Services',
        county: 'Marion',
        state: 'IN',
        address: '2600 S Harding St, Indianapolis, IN 46221',
        phone: '(317) 327-1397',
        websiteUrl: 'https://www.indy.gov/agency/animal-care-services',
        totalIntakeAnnual: 12000, totalEuthanizedAnnual: 2400,
        dataYear: 2024, dataSourceName: 'Indy ACS', dataSourceUrl: 'https://www.indy.gov/agency/animal-care-services',
        countyPopulation: 977203, totalReturnedToOwner: 1500, totalTransferred: 2000,
        priorYearIntake: 11500, priorYearEuthanized: 2415, priorDataYear: 2023,
    },
    {
        name: 'Fort Wayne Animal Care & Control',
        county: 'Allen',
        state: 'IN',
        address: '3020 Hillegas Rd, Fort Wayne, IN 46808',
        phone: '(260) 427-1244',
        websiteUrl: 'https://www.fortwayneanimalcare.org',
        totalIntakeAnnual: 5500, totalEuthanizedAnnual: 825,
        dataYear: 2024, dataSourceName: 'Fort Wayne ACC', dataSourceUrl: 'https://www.fortwayneanimalcare.org',
        countyPopulation: 385723, totalReturnedToOwner: 700, totalTransferred: 800,
        priorYearIntake: 5300, priorYearEuthanized: 795, priorDataYear: 2023,
    },
    {
        name: 'Lake County Animal Control',
        county: 'Lake',
        state: 'IN',
        address: '6655 Broadway, Merrillville, IN 46410',
        phone: '(219) 755-3685',
        websiteUrl: 'https://www.lakecountyin.org/portal/media-type/html/group/Animal+Adoption+Control',
        totalIntakeAnnual: 4500, totalEuthanizedAnnual: 900,
        dataYear: 2024, dataSourceName: 'Lake County AC', dataSourceUrl: 'https://www.lakecountyin.org',
        countyPopulation: 498700, totalReturnedToOwner: 500, totalTransferred: 600,
        priorYearIntake: 4300, priorYearEuthanized: 860, priorDataYear: 2023,
    },
    {
        name: 'Hamilton County Humane Society',
        county: 'Hamilton',
        state: 'IN',
        address: '1721 Pleasant St, Noblesville, IN 46060',
        phone: '(317) 773-4974',
        websiteUrl: 'https://www.hamiltonhumane.com',
        totalIntakeAnnual: 3500, totalEuthanizedAnnual: 175,
        dataYear: 2024, dataSourceName: 'Hamilton Humane', dataSourceUrl: 'https://www.hamiltonhumane.com/about/',
        countyPopulation: 338011, totalReturnedToOwner: 500, totalTransferred: 400,
        priorYearIntake: 3400, priorYearEuthanized: 170, priorDataYear: 2023,
    },
    {
        name: 'Vanderburgh Humane Society',
        county: 'Vanderburgh',
        state: 'IN',
        address: '400 Millner Industrial Dr, Evansville, IN 47710',
        phone: '(812) 426-2563',
        websiteUrl: 'https://www.vfrhs.org',
        totalIntakeAnnual: 3800, totalEuthanizedAnnual: 570,
        dataYear: 2024, dataSourceName: 'Vanderburgh Humane', dataSourceUrl: 'https://www.vfrhs.org',
        countyPopulation: 181877, totalReturnedToOwner: 400, totalTransferred: 450,
        priorYearIntake: 3700, priorYearEuthanized: 555, priorDataYear: 2023,
    },
];
