import type { ShelterSeedData } from './california-shelters';

export const louisianaShelters: ShelterSeedData[] = [
    {
        name: 'Louisiana SPCA',
        county: 'Orleans Parish',
        state: 'LA',
        address: '1700 Mardi Gras Blvd, New Orleans, LA 70114',
        phone: '(504) 368-5191',
        websiteUrl: 'https://www.la-spca.org',
        totalIntakeAnnual: 7500,
        totalEuthanizedAnnual: 750,
        dataYear: 2024,
        dataSourceName: 'Louisiana SPCA',
        dataSourceUrl: 'https://www.la-spca.org/about',
        countyPopulation: 383997,
        totalReturnedToOwner: 900,
        totalTransferred: 1100,
        priorYearIntake: 7200,
        priorYearEuthanized: 720,
        priorDataYear: 2023,
    },
    {
        name: 'East Baton Rouge Animal Control',
        county: 'East Baton Rouge Parish',
        state: 'LA',
        address: '2680 Progress Rd, Baton Rouge, LA 70807',
        phone: '(225) 774-7700',
        websiteUrl: 'https://www.brla.gov/179/Animal-Control',
        totalIntakeAnnual: 8000,
        totalEuthanizedAnnual: 2000,
        dataYear: 2024,
        dataSourceName: 'EBR Animal Control',
        dataSourceUrl: 'https://www.brla.gov/179/Animal-Control',
        countyPopulation: 456781,
        totalReturnedToOwner: 800,
        totalTransferred: 900,
        priorYearIntake: 7800,
        priorYearEuthanized: 2028,
        priorDataYear: 2023,
    },
    {
        name: 'Caddo Parish Animal Services',
        county: 'Caddo Parish',
        state: 'LA',
        address: '1500 Monty St, Shreveport, LA 71101',
        phone: '(318) 226-6624',
        websiteUrl: 'https://www.caddo.org/258/Animal-Services',
        totalIntakeAnnual: 6000,
        totalEuthanizedAnnual: 1800,
        dataYear: 2024,
        dataSourceName: 'Caddo Parish Government',
        dataSourceUrl: 'https://www.caddo.org/258/Animal-Services',
        countyPopulation: 248361,
        totalReturnedToOwner: 500,
        totalTransferred: 600,
        priorYearIntake: 5800,
        priorYearEuthanized: 1798,
        priorDataYear: 2023,
    },
    {
        name: 'Jefferson Parish Animal Shelter',
        county: 'Jefferson Parish',
        state: 'LA',
        address: '1 Eiffel Tower Dr, Harahan, LA 70123',
        phone: '(504) 736-6111',
        websiteUrl: 'https://www.jeffparish.net/departments/animal-shelter',
        totalIntakeAnnual: 5500,
        totalEuthanizedAnnual: 1375,
        dataYear: 2024,
        dataSourceName: 'Jefferson Parish Government',
        dataSourceUrl: 'https://www.jeffparish.net/departments/animal-shelter',
        countyPopulation: 440781,
        totalReturnedToOwner: 600,
        totalTransferred: 700,
        priorYearIntake: 5300,
        priorYearEuthanized: 1378,
        priorDataYear: 2023,
    },
    {
        name: 'Lafayette Animal Shelter & Care Center',
        county: 'Lafayette Parish',
        state: 'LA',
        address: '410 Dugas Rd, Lafayette, LA 70507',
        phone: '(337) 291-5644',
        websiteUrl: 'https://www.lafayettela.gov/animal-shelter-and-care-center',
        totalIntakeAnnual: 5000,
        totalEuthanizedAnnual: 1250,
        dataYear: 2024,
        dataSourceName: 'Lafayette Animal Shelter',
        dataSourceUrl: 'https://www.lafayettela.gov/animal-shelter-and-care-center',
        countyPopulation: 241753,
        totalReturnedToOwner: 500,
        totalTransferred: 600,
        priorYearIntake: 4800,
        priorYearEuthanized: 1248,
        priorDataYear: 2023,
    },
];
