import type { ShelterSeedData } from './california-shelters';

export const michiganShelters: ShelterSeedData[] = [
    {
        name: 'Detroit Animal Care & Control',
        county: 'Wayne',
        state: 'MI',
        address: '7401 Chrysler Dr, Detroit, MI 48211',
        phone: '(313) 922-3636',
        websiteUrl: 'https://detroitmi.gov/departments/detroit-animal-care-control',
        totalIntakeAnnual: 8000,
        totalEuthanizedAnnual: 1600,
        dataYear: 2024,
        dataSourceName: 'Detroit ACC',
        dataSourceUrl: 'https://detroitmi.gov/departments/detroit-animal-care-control',
        countyPopulation: 1793561,
        totalReturnedToOwner: 800,
        totalTransferred: 1200,
        priorYearIntake: 7800,
        priorYearEuthanized: 1638,
        priorDataYear: 2023,
    },
    {
        name: 'Kent County Animal Shelter',
        county: 'Kent',
        state: 'MI',
        address: '740 Fuller Ave NE, Grand Rapids, MI 49503',
        phone: '(616) 632-7300',
        websiteUrl: 'https://www.accesskent.com/Health/AnimalShelter/',
        totalIntakeAnnual: 5000,
        totalEuthanizedAnnual: 500,
        dataYear: 2024,
        dataSourceName: 'Kent County Animal Shelter',
        dataSourceUrl: 'https://www.accesskent.com/Health/AnimalShelter/',
        countyPopulation: 657974,
        totalReturnedToOwner: 800,
        totalTransferred: 700,
        priorYearIntake: 4800,
        priorYearEuthanized: 480,
        priorDataYear: 2023,
    },
    {
        name: 'Michigan Humane (Detroit)',
        county: 'Wayne',
        state: 'MI',
        address: '900 N Newburgh Rd, Westland, MI 48185',
        phone: '(866) 648-6263',
        websiteUrl: 'https://www.michiganhumane.org',
        totalIntakeAnnual: 10000,
        totalEuthanizedAnnual: 1000,
        dataYear: 2024,
        dataSourceName: 'Michigan Humane',
        dataSourceUrl: 'https://www.michiganhumane.org/about/',
        countyPopulation: 1793561,
        totalReturnedToOwner: 1200,
        totalTransferred: 1500,
        priorYearIntake: 9800,
        priorYearEuthanized: 980,
        priorDataYear: 2023,
    },
    {
        name: 'Washtenaw County Animal Control',
        county: 'Washtenaw',
        state: 'MI',
        address: '7255 Jackson Rd, Ann Arbor, MI 48103',
        phone: '(734) 971-6335',
        websiteUrl: 'https://www.washtenaw.org/312/Animal-Control',
        totalIntakeAnnual: 3500,
        totalEuthanizedAnnual: 350,
        dataYear: 2024,
        dataSourceName: 'Washtenaw County Government',
        dataSourceUrl: 'https://www.washtenaw.org/312/Animal-Control',
        countyPopulation: 372258,
        totalReturnedToOwner: 500,
        totalTransferred: 450,
        priorYearIntake: 3400,
        priorYearEuthanized: 340,
        priorDataYear: 2023,
    },
    {
        name: 'Genesee County Animal Control',
        county: 'Genesee',
        state: 'MI',
        address: '4351 W Pasadena Ave, Flint, MI 48504',
        phone: '(810) 732-1660',
        websiteUrl: 'https://www.gc4me.com/departments/animal_control/',
        totalIntakeAnnual: 4500,
        totalEuthanizedAnnual: 900,
        dataYear: 2024,
        dataSourceName: 'Genesee County Animal Control',
        dataSourceUrl: 'https://www.gc4me.com/departments/animal_control/',
        countyPopulation: 406892,
        totalReturnedToOwner: 500,
        totalTransferred: 500,
        priorYearIntake: 4300,
        priorYearEuthanized: 860,
        priorDataYear: 2023,
    },
    {
        name: 'Ingham County Animal Control',
        county: 'Ingham',
        state: 'MI',
        address: '600 Buhl St, Mason, MI 48854',
        phone: '(517) 676-8370',
        websiteUrl: 'https://ac.ingham.org',
        totalIntakeAnnual: 3200,
        totalEuthanizedAnnual: 480,
        dataYear: 2024,
        dataSourceName: 'Ingham County Animal Control',
        dataSourceUrl: 'https://ac.ingham.org',
        countyPopulation: 284900,
        totalReturnedToOwner: 400,
        totalTransferred: 400,
        priorYearIntake: 3100,
        priorYearEuthanized: 465,
        priorDataYear: 2023,
    },
];
