import type { ShelterSeedData } from './california-shelters';

export const missouriShelters: ShelterSeedData[] = [
    {
        name: 'Kansas City Pet Project',
        county: 'Jackson', state: 'MO',
        address: '4400 Raytown Rd, Kansas City, MO 64129', phone: '(816) 683-1383',
        websiteUrl: 'https://kcpetproject.org',
        totalIntakeAnnual: 11000, totalEuthanizedAnnual: 1100,
        dataYear: 2024, dataSourceName: 'KC Pet Project', dataSourceUrl: 'https://kcpetproject.org/about-us/',
        countyPopulation: 717204, totalReturnedToOwner: 1500, totalTransferred: 1800,
        priorYearIntake: 10500, priorYearEuthanized: 1050, priorDataYear: 2023,
    },
    {
        name: 'St. Louis City Animal Care & Control',
        county: 'St. Louis City', state: 'MO',
        address: '1920 S Broadway, St. Louis, MO 63104', phone: '(314) 657-1500',
        websiteUrl: 'https://www.stlouis-mo.gov/government/departments/health/animal-care-control/',
        totalIntakeAnnual: 6000, totalEuthanizedAnnual: 1200,
        dataYear: 2024, dataSourceName: 'STL ACC', dataSourceUrl: 'https://www.stlouis-mo.gov/government/departments/health/animal-care-control/',
        countyPopulation: 293310, totalReturnedToOwner: 600, totalTransferred: 700,
        priorYearIntake: 5800, priorYearEuthanized: 1218, priorDataYear: 2023,
    },
    {
        name: 'St. Louis County Animal Care & Control',
        county: 'St. Louis', state: 'MO',
        address: '10521 Baur Blvd, Olivette, MO 63132', phone: '(314) 615-0934',
        websiteUrl: 'https://stlouiscountymo.gov/st-louis-county-departments/police/animal-care-control/',
        totalIntakeAnnual: 5500, totalEuthanizedAnnual: 825,
        dataYear: 2024, dataSourceName: 'STL County ACC', dataSourceUrl: 'https://stlouiscountymo.gov/st-louis-county-departments/police/animal-care-control/',
        countyPopulation: 1004125, totalReturnedToOwner: 700, totalTransferred: 600,
        priorYearIntake: 5300, priorYearEuthanized: 795, priorDataYear: 2023,
    },
    {
        name: 'Springfield Animal Shelter',
        county: 'Greene', state: 'MO',
        address: '4002 N Farmer, Springfield, MO 65803', phone: '(417) 833-3592',
        websiteUrl: 'https://www.springfieldmo.gov/1556/Animal-Shelter',
        totalIntakeAnnual: 4500, totalEuthanizedAnnual: 900,
        dataYear: 2024, dataSourceName: 'Springfield Animal Shelter', dataSourceUrl: 'https://www.springfieldmo.gov/1556/Animal-Shelter',
        countyPopulation: 293086, totalReturnedToOwner: 500, totalTransferred: 500,
        priorYearIntake: 4300, priorYearEuthanized: 860, priorDataYear: 2023,
    },
    {
        name: 'Columbia / Boone County Animal Control',
        county: 'Boone', state: 'MO',
        address: '616 Big Bear Blvd, Columbia, MO 65202', phone: '(573) 875-6621',
        websiteUrl: 'https://www.como.gov/CMS/animal/',
        totalIntakeAnnual: 3200, totalEuthanizedAnnual: 480,
        dataYear: 2024, dataSourceName: 'Columbia AC', dataSourceUrl: 'https://www.como.gov/CMS/animal/',
        countyPopulation: 183610, totalReturnedToOwner: 400, totalTransferred: 350,
        priorYearIntake: 3100, priorYearEuthanized: 465, priorDataYear: 2023,
    },
];
