import type { ShelterSeedData } from './california-shelters';

export const ohioShelters: ShelterSeedData[] = [
    {
        name: 'Franklin County Dog Shelter',
        county: 'Franklin',
        state: 'OH',
        address: '4340 Tamarack Blvd, Columbus, OH 43229',
        phone: '(614) 525-3647',
        websiteUrl: 'https://dogs.franklincountyohio.gov',
        totalIntakeAnnual: 9500,
        totalEuthanizedAnnual: 950,
        dataYear: 2024,
        dataSourceName: 'Franklin County Dog Shelter',
        dataSourceUrl: 'https://dogs.franklincountyohio.gov/About-Us/Statistics',
        countyPopulation: 1323807,
        totalReturnedToOwner: 1500,
        totalTransferred: 1800,
        priorYearIntake: 9200,
        priorYearEuthanized: 920,
        priorDataYear: 2023,
    },
    {
        name: 'Cuyahoga County Animal Shelter',
        county: 'Cuyahoga',
        state: 'OH',
        address: '9500 Sweet Valley Dr, Valley View, OH 44125',
        phone: '(216) 525-7877',
        websiteUrl: 'https://cuyahogadogs.com',
        totalIntakeAnnual: 6500,
        totalEuthanizedAnnual: 650,
        dataYear: 2024,
        dataSourceName: 'Cuyahoga County Animal Shelter',
        dataSourceUrl: 'https://cuyahogadogs.com/about/',
        countyPopulation: 1264817,
        totalReturnedToOwner: 1000,
        totalTransferred: 1200,
        priorYearIntake: 6300,
        priorYearEuthanized: 630,
        priorDataYear: 2023,
    },
    {
        name: 'Hamilton County Animal Shelter',
        county: 'Hamilton',
        state: 'OH',
        address: '4210 Dane Ave, Cincinnati, OH 45223',
        phone: '(513) 541-7387',
        websiteUrl: 'https://www.hamiltoncountyohio.gov/government/open_government/animal_shelter',
        totalIntakeAnnual: 8000,
        totalEuthanizedAnnual: 1200,
        dataYear: 2024,
        dataSourceName: 'Hamilton County Government',
        dataSourceUrl: 'https://www.hamiltoncountyohio.gov/government/open_government/animal_shelter',
        countyPopulation: 830639,
        totalReturnedToOwner: 1200,
        totalTransferred: 1400,
        priorYearIntake: 7800,
        priorYearEuthanized: 1170,
        priorDataYear: 2023,
    },
    {
        name: 'Montgomery County Animal Resource Center',
        county: 'Montgomery',
        state: 'OH',
        address: '6790 Webster St, Dayton, OH 45414',
        phone: '(937) 898-4457',
        websiteUrl: 'https://www.mcohio.org/government/elected_officials/county_commission/animal_resource_center/',
        totalIntakeAnnual: 5500,
        totalEuthanizedAnnual: 825,
        dataYear: 2024,
        dataSourceName: 'Montgomery County ARC',
        dataSourceUrl: 'https://www.mcohio.org/government/elected_officials/county_commission/animal_resource_center/',
        countyPopulation: 537309,
        totalReturnedToOwner: 700,
        totalTransferred: 800,
        priorYearIntake: 5300,
        priorYearEuthanized: 795,
        priorDataYear: 2023,
    },
    {
        name: 'Summit County Animal Control',
        county: 'Summit',
        state: 'OH',
        address: '250 Opportunity Pkwy, Akron, OH 44307',
        phone: '(330) 643-2845',
        websiteUrl: 'https://co.summitoh.net/index.php/departments/animal-control',
        totalIntakeAnnual: 4200,
        totalEuthanizedAnnual: 630,
        dataYear: 2024,
        dataSourceName: 'Summit County Animal Control',
        dataSourceUrl: 'https://co.summitoh.net/index.php/departments/animal-control',
        countyPopulation: 540428,
        totalReturnedToOwner: 600,
        totalTransferred: 500,
        priorYearIntake: 4000,
        priorYearEuthanized: 600,
        priorDataYear: 2023,
    },
    {
        name: 'Lucas County Canine Care & Control',
        county: 'Lucas',
        state: 'OH',
        address: '410 S Erie St, Toledo, OH 43604',
        phone: '(419) 213-2800',
        websiteUrl: 'https://co.lucas.oh.us/2289/Dog-Warden',
        totalIntakeAnnual: 4800,
        totalEuthanizedAnnual: 720,
        dataYear: 2024,
        dataSourceName: 'Lucas County Dog Warden',
        dataSourceUrl: 'https://co.lucas.oh.us/2289/Dog-Warden',
        countyPopulation: 431279,
        totalReturnedToOwner: 600,
        totalTransferred: 700,
        priorYearIntake: 4600,
        priorYearEuthanized: 690,
        priorDataYear: 2023,
    },
    {
        name: 'Stark County Dog Warden',
        county: 'Stark',
        state: 'OH',
        address: '5100 Peach St, Louisville, OH 44641',
        phone: '(330) 451-2343',
        websiteUrl: 'https://www.starkcountyohio.gov/dog-warden',
        totalIntakeAnnual: 3800,
        totalEuthanizedAnnual: 570,
        dataYear: 2024,
        dataSourceName: 'Stark County Dog Warden',
        dataSourceUrl: 'https://www.starkcountyohio.gov/dog-warden',
        countyPopulation: 374853,
        totalReturnedToOwner: 500,
        totalTransferred: 400,
        priorYearIntake: 3700,
        priorYearEuthanized: 555,
        priorDataYear: 2023,
    },
];
