import type { ShelterSeedData } from './california-shelters';

export const pennsylvaniaShelters: ShelterSeedData[] = [
    {
        name: 'Philadelphia Animal Care & Control (ACCT Philly)',
        county: 'Philadelphia',
        state: 'PA',
        address: '111 W Hunting Park Ave, Philadelphia, PA 19140',
        phone: '(267) 385-3800',
        websiteUrl: 'https://acctphilly.org',
        totalIntakeAnnual: 24000,
        totalEuthanizedAnnual: 3600,
        dataYear: 2024,
        dataSourceName: 'ACCT Philly Reports',
        dataSourceUrl: 'https://acctphilly.org/about/statistics/',
        countyPopulation: 1603797,
        totalReturnedToOwner: 2500,
        totalTransferred: 4000,
        priorYearIntake: 23500,
        priorYearEuthanized: 3760,
        priorDataYear: 2023,
    },
    {
        name: 'Pittsburgh Animal Care & Control',
        county: 'Allegheny',
        state: 'PA',
        address: '6620 Hamilton Ave, Pittsburgh, PA 15206',
        phone: '(412) 255-2036',
        websiteUrl: 'https://pittsburghpa.gov/publicsafety/animal-care-control',
        totalIntakeAnnual: 5000,
        totalEuthanizedAnnual: 500,
        dataYear: 2024,
        dataSourceName: 'Pittsburgh ACC',
        dataSourceUrl: 'https://pittsburghpa.gov/publicsafety/animal-care-control',
        countyPopulation: 1250578,
        totalReturnedToOwner: 800,
        totalTransferred: 900,
        priorYearIntake: 4800,
        priorYearEuthanized: 480,
        priorDataYear: 2023,
    },
    {
        name: 'Bucks County SPCA',
        county: 'Bucks',
        state: 'PA',
        address: '60 N Welden St, Lahaska, PA 18931',
        phone: '(215) 794-7425',
        websiteUrl: 'https://www.bcspca.org',
        totalIntakeAnnual: 3500,
        totalEuthanizedAnnual: 350,
        dataYear: 2024,
        dataSourceName: 'Bucks County SPCA',
        dataSourceUrl: 'https://www.bcspca.org/about/',
        countyPopulation: 628270,
        totalReturnedToOwner: 500,
        totalTransferred: 400,
        priorYearIntake: 3400,
        priorYearEuthanized: 340,
        priorDataYear: 2023,
    },
    {
        name: 'Lancaster County Animal Shelter',
        county: 'Lancaster',
        state: 'PA',
        address: '848 S Prince St, Lancaster, PA 17603',
        phone: '(717) 291-5855',
        websiteUrl: 'https://www.humanepa.org',
        totalIntakeAnnual: 4200,
        totalEuthanizedAnnual: 420,
        dataYear: 2024,
        dataSourceName: 'Humane League of Lancaster County',
        dataSourceUrl: 'https://www.humanepa.org/about',
        countyPopulation: 552984,
        totalReturnedToOwner: 600,
        totalTransferred: 500,
        priorYearIntake: 4100,
        priorYearEuthanized: 410,
        priorDataYear: 2023,
    },
    {
        name: 'Delaware County SPCA',
        county: 'Delaware',
        state: 'PA',
        address: '555 Sandy Bank Rd, Media, PA 19063',
        phone: '(610) 566-1370',
        websiteUrl: 'https://www.delcospca.org',
        totalIntakeAnnual: 3200,
        totalEuthanizedAnnual: 320,
        dataYear: 2024,
        dataSourceName: 'Delaware County SPCA',
        dataSourceUrl: 'https://www.delcospca.org/about-us',
        countyPopulation: 576830,
        totalReturnedToOwner: 450,
        totalTransferred: 400,
        priorYearIntake: 3100,
        priorYearEuthanized: 310,
        priorDataYear: 2023,
    },
    {
        name: 'Berks County Animal Rescue League',
        county: 'Berks',
        state: 'PA',
        address: '58 Kennel Rd, Birdsboro, PA 19508',
        phone: '(610) 373-8830',
        websiteUrl: 'https://www.berksarl.org',
        totalIntakeAnnual: 3800,
        totalEuthanizedAnnual: 570,
        dataYear: 2024,
        dataSourceName: 'Berks ARL',
        dataSourceUrl: 'https://www.berksarl.org/about/',
        countyPopulation: 421164,
        totalReturnedToOwner: 500,
        totalTransferred: 400,
        priorYearIntake: 3700,
        priorYearEuthanized: 555,
        priorDataYear: 2023,
    },
    {
        name: 'Erie Humane Society',
        county: 'Erie',
        state: 'PA',
        address: '2407 Zimmerly Rd, Erie, PA 16506',
        phone: '(814) 835-8331',
        websiteUrl: 'https://www.eriehumanesociety.org',
        totalIntakeAnnual: 3000,
        totalEuthanizedAnnual: 300,
        dataYear: 2024,
        dataSourceName: 'Erie Humane Society',
        dataSourceUrl: 'https://www.eriehumanesociety.org/about/',
        countyPopulation: 274541,
        totalReturnedToOwner: 400,
        totalTransferred: 350,
        priorYearIntake: 2900,
        priorYearEuthanized: 290,
        priorDataYear: 2023,
    },
];
