import type { ShelterSeedData } from './california-shelters';

export const southCarolinaShelters: ShelterSeedData[] = [
    {
        name: 'Greenville County Animal Care',
        county: 'Greenville',
        state: 'SC',
        address: '328 Furman Hall Rd, Greenville, SC 29609',
        phone: '(864) 467-3950',
        websiteUrl: 'https://www.greenvillecounty.org/acs/',
        totalIntakeAnnual: 7500,
        totalEuthanizedAnnual: 1875,
        dataYear: 2024,
        dataSourceName: 'Greenville County ACS',
        dataSourceUrl: 'https://www.greenvillecounty.org/acs/',
        countyPopulation: 523542,
        totalReturnedToOwner: 900,
        totalTransferred: 1000,
        priorYearIntake: 7200,
        priorYearEuthanized: 1872,
        priorDataYear: 2023,
    },
    {
        name: 'Charleston Animal Society',
        county: 'Charleston',
        state: 'SC',
        address: '2455 Remount Rd, North Charleston, SC 29406',
        phone: '(843) 747-4849',
        websiteUrl: 'https://www.charlestonanimalsociety.org',
        totalIntakeAnnual: 9000,
        totalEuthanizedAnnual: 900,
        dataYear: 2024,
        dataSourceName: 'Charleston Animal Society',
        dataSourceUrl: 'https://www.charlestonanimalsociety.org/about-us/',
        countyPopulation: 408235,
        totalReturnedToOwner: 1200,
        totalTransferred: 1500,
        priorYearIntake: 8800,
        priorYearEuthanized: 880,
        priorDataYear: 2023,
    },
    {
        name: 'Richland County Animal Care',
        county: 'Richland',
        state: 'SC',
        address: '400 Powell Rd, Columbia, SC 29203',
        phone: '(803) 576-2424',
        websiteUrl: 'https://www.richlandcountysc.gov/Government/Departments/Animal-Care',
        totalIntakeAnnual: 6000,
        totalEuthanizedAnnual: 1500,
        dataYear: 2024,
        dataSourceName: 'Richland County Government',
        dataSourceUrl: 'https://www.richlandcountysc.gov/Government/Departments/Animal-Care',
        countyPopulation: 415759,
        totalReturnedToOwner: 600,
        totalTransferred: 700,
        priorYearIntake: 5800,
        priorYearEuthanized: 1508,
        priorDataYear: 2023,
    },
    {
        name: 'Spartanburg Humane Society',
        county: 'Spartanburg',
        state: 'SC',
        address: '150 Dexter Rd, Spartanburg, SC 29303',
        phone: '(864) 583-4805',
        websiteUrl: 'https://www.spartanburghumane.org',
        totalIntakeAnnual: 5500,
        totalEuthanizedAnnual: 1375,
        dataYear: 2024,
        dataSourceName: 'Spartanburg Humane Society',
        dataSourceUrl: 'https://www.spartanburghumane.org/about/',
        countyPopulation: 327997,
        totalReturnedToOwner: 500,
        totalTransferred: 600,
        priorYearIntake: 5300,
        priorYearEuthanized: 1378,
        priorDataYear: 2023,
    },
    {
        name: 'Anderson County PAWS',
        county: 'Anderson',
        state: 'SC',
        address: '1725 Williamston Rd, Anderson, SC 29621',
        phone: '(864) 260-4151',
        websiteUrl: 'https://www.andersoncountysc.org/animal-shelter',
        totalIntakeAnnual: 4000,
        totalEuthanizedAnnual: 1200,
        dataYear: 2024,
        dataSourceName: 'Anderson County PAWS',
        dataSourceUrl: 'https://www.andersoncountysc.org/animal-shelter',
        countyPopulation: 204250,
        totalReturnedToOwner: 400,
        totalTransferred: 450,
        priorYearIntake: 3900,
        priorYearEuthanized: 1209,
        priorDataYear: 2023,
    },
    {
        name: 'Horry County Animal Care Center',
        county: 'Horry',
        state: 'SC',
        address: '1923 Industrial Park Rd, Conway, SC 29526',
        phone: '(843) 915-5172',
        websiteUrl: 'https://www.horrycounty.org/departments/animal-care-center',
        totalIntakeAnnual: 5000,
        totalEuthanizedAnnual: 1250,
        dataYear: 2024,
        dataSourceName: 'Horry County ACC',
        dataSourceUrl: 'https://www.horrycounty.org/departments/animal-care-center',
        countyPopulation: 354081,
        totalReturnedToOwner: 500,
        totalTransferred: 600,
        priorYearIntake: 4800,
        priorYearEuthanized: 1248,
        priorDataYear: 2023,
    },
];
