import type { ShelterSeedData } from './california-shelters';

export const tennesseeShelters: ShelterSeedData[] = [
    {
        name: 'Memphis Animal Services',
        county: 'Shelby',
        state: 'TN',
        address: '3456 Tchulahoma Rd, Memphis, TN 38118',
        phone: '(901) 636-1416',
        websiteUrl: 'https://www.memphistn.gov/government/memphis-animal-services/',
        totalIntakeAnnual: 15000,
        totalEuthanizedAnnual: 3750,
        dataYear: 2024,
        dataSourceName: 'Memphis Animal Services',
        dataSourceUrl: 'https://www.memphistn.gov/government/memphis-animal-services/',
        countyPopulation: 929744,
        totalReturnedToOwner: 1500,
        totalTransferred: 2000,
        priorYearIntake: 14500,
        priorYearEuthanized: 3770,
        priorDataYear: 2023,
    },
    {
        name: 'Metro Nashville Animal Care & Control',
        county: 'Davidson',
        state: 'TN',
        address: '5125 Harding Pl, Nashville, TN 37211',
        phone: '(615) 862-7928',
        websiteUrl: 'https://www.nashville.gov/departments/health/animal-care-and-control',
        totalIntakeAnnual: 12000,
        totalEuthanizedAnnual: 1200,
        dataYear: 2024,
        dataSourceName: 'Metro Nashville ACC',
        dataSourceUrl: 'https://www.nashville.gov/departments/health/animal-care-and-control',
        countyPopulation: 715884,
        totalReturnedToOwner: 1800,
        totalTransferred: 2200,
        priorYearIntake: 11500,
        priorYearEuthanized: 1150,
        priorDataYear: 2023,
    },
    {
        name: 'Knox County Animal Control',
        county: 'Knox',
        state: 'TN',
        address: '3201 Division St, Knoxville, TN 37919',
        phone: '(865) 215-6599',
        websiteUrl: 'https://www.knoxvilletn.gov/government/city_departments_offices/animal_control',
        totalIntakeAnnual: 5500,
        totalEuthanizedAnnual: 825,
        dataYear: 2024,
        dataSourceName: 'Knox County Animal Control',
        dataSourceUrl: 'https://www.knoxvilletn.gov/government/city_departments_offices/animal_control',
        countyPopulation: 478971,
        totalReturnedToOwner: 700,
        totalTransferred: 800,
        priorYearIntake: 5300,
        priorYearEuthanized: 795,
        priorDataYear: 2023,
    },
    {
        name: 'Hamilton County Animal Services',
        county: 'Hamilton',
        state: 'TN',
        address: '6399 Lee Hwy, Chattanooga, TN 37421',
        phone: '(423) 305-6500',
        websiteUrl: 'https://hcde.org/animal-services',
        totalIntakeAnnual: 5000,
        totalEuthanizedAnnual: 750,
        dataYear: 2024,
        dataSourceName: 'Hamilton County Government',
        dataSourceUrl: 'https://hcde.org/animal-services',
        countyPopulation: 366207,
        totalReturnedToOwner: 600,
        totalTransferred: 700,
        priorYearIntake: 4800,
        priorYearEuthanized: 720,
        priorDataYear: 2023,
    },
    {
        name: 'Rutherford County Animal Control',
        county: 'Rutherford',
        state: 'TN',
        address: '285 John R Rice Blvd, Murfreesboro, TN 37129',
        phone: '(615) 898-7740',
        websiteUrl: 'https://www.rutherfordcountytn.gov/departments/animal-control',
        totalIntakeAnnual: 4000,
        totalEuthanizedAnnual: 800,
        dataYear: 2024,
        dataSourceName: 'Rutherford County Government',
        dataSourceUrl: 'https://www.rutherfordcountytn.gov/departments/animal-control',
        countyPopulation: 341486,
        totalReturnedToOwner: 400,
        totalTransferred: 500,
        priorYearIntake: 3800,
        priorYearEuthanized: 798,
        priorDataYear: 2023,
    },
    {
        name: 'Montgomery County Animal Care & Control',
        county: 'Montgomery',
        state: 'TN',
        address: '616 N Spring St, Clarksville, TN 37040',
        phone: '(931) 648-5750',
        websiteUrl: 'https://www.mcgtn.org/animal-control',
        totalIntakeAnnual: 4500,
        totalEuthanizedAnnual: 900,
        dataYear: 2024,
        dataSourceName: 'Montgomery County ACC',
        dataSourceUrl: 'https://www.mcgtn.org/animal-control',
        countyPopulation: 220069,
        totalReturnedToOwner: 450,
        totalTransferred: 550,
        priorYearIntake: 4300,
        priorYearEuthanized: 903,
        priorDataYear: 2023,
    },
];
