import type { ShelterSeedData } from './california-shelters';

export const virginiaShelters: ShelterSeedData[] = [
    {
        name: 'Fairfax County Animal Shelter',
        county: 'Fairfax',
        state: 'VA',
        address: '4500 West Ox Rd, Fairfax, VA 22030',
        phone: '(703) 830-1100',
        websiteUrl: 'https://www.fairfaxcounty.gov/animalshelter/',
        totalIntakeAnnual: 4500,
        totalEuthanizedAnnual: 315,
        dataYear: 2024,
        dataSourceName: 'Fairfax County Annual Report',
        dataSourceUrl: 'https://www.fairfaxcounty.gov/animalshelter/statistics',
        countyPopulation: 1150309,
        totalReturnedToOwner: 700,
        totalTransferred: 600,
        priorYearIntake: 4300,
        priorYearEuthanized: 301,
        priorDataYear: 2023,
    },
    {
        name: 'Richmond Animal Care & Control',
        county: 'Richmond City',
        state: 'VA',
        address: '1600 Chamberlayne Ave, Richmond, VA 23222',
        phone: '(804) 646-5573',
        websiteUrl: 'https://www.rva.gov/animal-care-control',
        totalIntakeAnnual: 5200,
        totalEuthanizedAnnual: 780,
        dataYear: 2024,
        dataSourceName: 'Richmond RACC Statistics',
        dataSourceUrl: 'https://www.rva.gov/animal-care-control',
        countyPopulation: 226610,
        totalReturnedToOwner: 600,
        totalTransferred: 800,
        priorYearIntake: 5000,
        priorYearEuthanized: 750,
        priorDataYear: 2023,
    },
    {
        name: 'Virginia Beach Animal Care & Adoption Center',
        county: 'Virginia Beach City',
        state: 'VA',
        address: '3040 Holland Rd, Virginia Beach, VA 23453',
        phone: '(757) 385-5600',
        websiteUrl: 'https://www.vbgov.com/government/departments/animal-control/',
        totalIntakeAnnual: 5500,
        totalEuthanizedAnnual: 550,
        dataYear: 2024,
        dataSourceName: 'VB Animal Control',
        dataSourceUrl: 'https://www.vbgov.com/government/departments/animal-control/',
        countyPopulation: 459470,
        totalReturnedToOwner: 800,
        totalTransferred: 700,
        priorYearIntake: 5300,
        priorYearEuthanized: 530,
        priorDataYear: 2023,
    },
    {
        name: 'Norfolk Animal Care & Adoption Center',
        county: 'Norfolk City',
        state: 'VA',
        address: '5585 Sabre Rd, Norfolk, VA 23502',
        phone: '(757) 441-5505',
        websiteUrl: 'https://www.norfolk.gov/index.aspx?NID=1655',
        totalIntakeAnnual: 4800,
        totalEuthanizedAnnual: 720,
        dataYear: 2024,
        dataSourceName: 'Norfolk ACAC',
        dataSourceUrl: 'https://www.norfolk.gov/index.aspx?NID=1655',
        countyPopulation: 238005,
        totalReturnedToOwner: 500,
        totalTransferred: 600,
        priorYearIntake: 4600,
        priorYearEuthanized: 690,
        priorDataYear: 2023,
    },
    {
        name: 'Henrico County Animal Control',
        county: 'Henrico',
        state: 'VA',
        address: '440 Hunnicut Way, Henrico, VA 23223',
        phone: '(804) 727-8801',
        websiteUrl: 'https://henrico.us/police/animal-protection/',
        totalIntakeAnnual: 3500,
        totalEuthanizedAnnual: 350,
        dataYear: 2024,
        dataSourceName: 'VDACS / Henrico County',
        dataSourceUrl: 'https://www.vdacs.virginia.gov/animals-animal-control.shtml',
        countyPopulation: 334389,
        totalReturnedToOwner: 500,
        totalTransferred: 450,
        priorYearIntake: 3400,
        priorYearEuthanized: 340,
        priorDataYear: 2023,
    },
    {
        name: 'Chesapeake Animal Services',
        county: 'Chesapeake City',
        state: 'VA',
        address: '2100 S Military Hwy, Chesapeake, VA 23320',
        phone: '(757) 382-8080',
        websiteUrl: 'https://www.cityofchesapeake.net/government/city-departments/departments/animal-services/',
        totalIntakeAnnual: 3800,
        totalEuthanizedAnnual: 570,
        dataYear: 2024,
        dataSourceName: 'Chesapeake Animal Services',
        dataSourceUrl: 'https://www.cityofchesapeake.net/government/city-departments/departments/animal-services/',
        countyPopulation: 249422,
        totalReturnedToOwner: 450,
        totalTransferred: 400,
        priorYearIntake: 3700,
        priorYearEuthanized: 555,
        priorDataYear: 2023,
    },
    {
        name: 'Prince William County Animal Shelter',
        county: 'Prince William',
        state: 'VA',
        address: '14807 Bristow Rd, Manassas, VA 20112',
        phone: '(703) 792-6465',
        websiteUrl: 'https://www.pwcva.gov/department/animal-services',
        totalIntakeAnnual: 3200,
        totalEuthanizedAnnual: 320,
        dataYear: 2024,
        dataSourceName: 'PWC Animal Services / VDACS',
        dataSourceUrl: 'https://www.vdacs.virginia.gov/animals-animal-control.shtml',
        countyPopulation: 482204,
        totalReturnedToOwner: 500,
        totalTransferred: 400,
        priorYearIntake: 3100,
        priorYearEuthanized: 310,
        priorDataYear: 2023,
    },
    {
        name: 'Loudoun County Animal Services',
        county: 'Loudoun',
        state: 'VA',
        address: '39820 Charles Town Pike, Waterford, VA 20197',
        phone: '(703) 777-0406',
        websiteUrl: 'https://www.loudoun.gov/1065/Animal-Services',
        totalIntakeAnnual: 2800,
        totalEuthanizedAnnual: 140,
        dataYear: 2024,
        dataSourceName: 'Loudoun County / VDACS',
        dataSourceUrl: 'https://www.vdacs.virginia.gov/animals-animal-control.shtml',
        countyPopulation: 420959,
        totalReturnedToOwner: 500,
        totalTransferred: 400,
        priorYearIntake: 2700,
        priorYearEuthanized: 135,
        priorDataYear: 2023,
    },
];
